@Server_HostAddress = http://localhost:5106

GET http://localhost:7163/flighthub/1
Accept: application/json

###

# buh passenger avah
GET {{Server_HostAddress}}/passenger
Accept: application/json

###


# Id - aar passenger avah
GET {{Server_HostAddress}}/passenger/1
Accept: application/json

###

# Бүх flight avah
GET {{Server_HostAddress}}/flight/
Accept: application/json

###

# Id-aar flight avah
GET {{Server_HostAddress}}/flight/2
Accept: application/json

###

# Post huselt flight
POST {{Server_HostAddress}}/flight/
Content-Type: application/json
Accept: application/json

{
  "flightNumber": "AA101",
  "status": "Delayed",
  "departure": "New York",
  "arrival": "Los Angeles",
  "departureTime": "2025-06-01T08:30:00",
  "arrivalTime": "2025-06-01T11:45:00",
  "seatCount": 30
}

###

# Id-aar flight delete hiih
DELETE {{Server_HostAddress}}/flight/2
Accept: application/json


###

# Id-aar flight update hiih
PUT {{Server_HostAddress}}/flight/
Content-Type: application/json
Accept: application/json

{
  "id": 2,
  "flightNumber": "AA101",
  "Status": "Flying",
  "departure": "Boston",
  "arrival": "Chicago",
  "departureTime": "2025-06-02T09:00:00",
  "arrivalTime": "2025-06-02T11:30:00"
}


###

# FlightId-aar Бүх seat avah
GET {{Server_HostAddress}}/seat/2
Accept: application/json


###

# Booking nemeh
POST {{Server_HostAddress}}/booking/
Content-Type: application/json
Accept: application/json

{
  "passengerId":1,
  "flightId": 1,
  "bookingDate": "2025-06-02T09:00:00"
}

###

# Buh booking avah
GET {{Server_HostAddress}}/booking/
Accept: application/json

###

# ID-aar booking avah
GET {{Server_HostAddress}}/booking/7
Accept: application/json

###


# Id-aar booking ustgah
DELETE {{Server_HostAddress}}/booking/2

###

# Id-aar booking update hiih buyu suudal onooh
PUT {{Server_HostAddress}}/booking/
Content-Type: application/json
Accept: application/json

{
  "id": 6,
  "passengerId":2,
  "flightId": 2,
  "bookingDate": "2025-06-02T09:00:00",
}

###

# Passport Id-aar booking avah
GET {{Server_HostAddress}}/booking/getByPassportId/1001
Accept: application/json